include:
  - project: 'cl-docker-images/ci-helpers'
    file: '/cl-docker-images-default-pipeline.yml'

variables:
  CANONICAL_NAMESPACE: daewok
  CL_DOCKER_IMAGES_AMD64: "1"
  CL_DOCKER_IMAGES_ARM64V8: "1"
  CL_DOCKER_IMAGES_WINAMD64: "1"
  WINDOWS_PARENT_IMAGES: "openjdk:15-windowsservercore-1809;openjdk:11-windowsservercore-1809;openjdk:8-windowsservercore-1809;openjdk:15-windowsservercore-ltsc2016;openjdk:11-windowsservercore-ltsc2016;openjdk:8-windowsservercore-ltsc2016"
