#+TITLE: ABCL Docker Images

This project contains Docker images to build ABCL and the infrastructure to
build the images as well as generate the manifest needed for inclusion in the
[[https://docs.docker.com/docker-hub/official_images/][Docker Official Images program]].

This repository is mirrored between both
[[https://gitlab.common-lisp.net/cl-docker-images/abcl]] and
[[https://github.com/cl-docker-images/abcl]]. The ABCL documentation for the
official images program is found on the =abcl= branch of
[[https://gitlab.common-lisp.net/cl-docker-images/docs]] (also mirrored to
Github). The ABCL manifest is found on the =abcl= branch of
[[https://gitlab.common-lisp.net/cl-docker-images/official-images]] (also mirrored
to Github).

* Unofficial images

  Currently, all images defined on the =master= branch are built and pushed to
  =daewok/abcl= on Docker Hub. This allows the images to be used and tested
  before they make their way into Official Images namepsace.

* Releasing a new version

  When a new version of ABCL is released, perform the following steps:

  1. Run the following command to generate the Dockerfiles:

     #+begin_src shell
       ./update.sh $ABCL_VERSION_NUMBER
     #+end_src

  2. Remove all folders for ABCL versions that are no longer
     supported. Reminder: the corresponding tags are *not* removed from
     Dockerhub, they will just no longer be automatically built.

  3. Update the version aliases as necessary in
     [[file:generate-stackbrew-library.sh]].

  4. Open a merge request on
     [[https://gitlab.common-lisp.net/cl-docker-images/abcl]] (preferred) or
     [[https://github.com/cl-docker-images/abcl]].

* Promoting a version to the Official Images Library

  1. Checkout the latest version of the =abcl= branch of
     [[https://gitlab.common-lisp.net/cl-docker-images/official-images]].

  2. Run the following command:

     #+begin_src shell
       ./generate-stackbrew-library.sh > $PATH_TO_OFFICIAL_IMAGES/library/abcl
     #+end_src

  3. Open a merge request with the change.
